project_id = "mbkfbmsjwlgqyzhfjwka"

[functions.autodesk-auth]
verify_jwt = false

[functions.autodesk-projects]
verify_jwt = false

[functions.autodesk-files]
verify_jwt = false

[functions.autodesk-viewer-token]
verify_jwt = false

[functions.autodesk-refresh-token]
verify_jwt = false

[functions.revit-modify]
verify_jwt = false

[functions.autodesk-reupload-ssa]
verify_jwt = false

[functions.reupload-file-ssa]
verify_jwt = false